### ISSUE TITLE
Compatibility with Strapi 4.6+

### ISSUE THREAD

**Issue by JWandscheer** [nicolashmln/strapi-plugin-responsive-image#25]
There seems to be an error in processing the formats after initial installation.
When opening the Settings page for responsive images, the page remains completely blank. Javascript console throws an Error:

```
[Error] TypeError: undefined is not an object (evaluating 'B.formats.map') — responsive-image-settings-page.0d723668.chunk.js:1:7998
	bu (main.ced25535.js:883)
	(anonyme Funktion) (main.ced25535.js:883:300)
	li (main.ced25535.js:881:43167)
	Rc (main.ced25535.js:883:2041)
	td (main.ced25535.js:885:5382)
	td
	(anonyme Funktion) (main.ced25535.js:909:3857)
	El (main.ced25535.js:885:1864)
	Iu (main.ced25535.js:883:11288)
	Iu
	(anonyme Funktion) (main.ced25535.js:881:39499)
	(anonyme Funktion) (main.ced25535.js:909:3857)
	Qs (main.ced25535.js:881:39446)
	xa (main.ced25535.js:881:39381)
	os (main.ced25535.js:883:8603)
	ql (main.ced25535.js:881:60254)
	ql
	(anonyme Funktion) (responsive-image-settings-page.0d723668.chunk.js:1:5275)
	asyncFunctionResume
	(anonyme Funktion)
	promiseReactionJobWithoutPromise
	promiseReactionJob
```

Trying to upload a new image to the media library throws the following error (in container logs):
```
backend-strapi-1  | [2023-02-13 13:56:22.549] error: Cannot destructure property 'formats' of '(intermediate value)' as it is null.
backend-strapi-1  | TypeError: Cannot destructure property 'formats' of '(intermediate value)' as it is null.
backend-strapi-1  |     at generateResponsiveFormats (/srv/app/node_modules/strapi-plugin-responsive-image/server/services/image-manipulation.js:88:11)
backend-strapi-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
backend-strapi-1  |     at async Object.uploadImage (/srv/app/node_modules/@strapi/plugin-upload/server/services/upload.js:228:23)
backend-strapi-1  |     at async Object.uploadFileAndPersist (/srv/app/node_modules/@strapi/plugin-upload/server/services/upload.js:251:7)
backend-strapi-1  |     at async Promise.all (index 0)
backend-strapi-1  |     at async Object.upload (/srv/app/node_modules/@strapi/plugin-upload/server/services/upload.js:173:23)
backend-strapi-1  |     at async uploadFiles (/srv/app/node_modules/@strapi/plugin-upload/server/controllers/admin-upload.js:75:27)
backend-strapi-1  |     at async Object.upload (/srv/app/node_modules/@strapi/plugin-upload/server/controllers/admin-upload.js:94:5)
backend-strapi-1  |     at async returnBodyMiddleware (/srv/app/node_modules/@strapi/strapi/lib/services/server/compose-endpoint.js:52:18)
backend-strapi-1  |     at async policiesMiddleware (/srv/app/node_modules/@strapi/strapi/lib/services/server/policy.js:24:5)
```

The Plugin is new added to the Strapi instance.

**System Information:**
Strapi v4.6.0 (Docker)
Postgres 15.1-1.pgdg110+1 (Docker)

_Other Installed Plugins_:
GraphQL
upload-plugin-cache
Roles & Permissions

Is this a known Problem or is this a misconfiguration f.e. missing initial formats in some config files after installation?

**Comment by JWandscheer** [comment]
Seems to need two restarts after installation. After complete Shutdown of all containers it is working.
